---
- name: Create storage location
  when: bareos_sd.location is defined
  file: 
    path: "{{ item.path }}"
    state: directory
    mode: '0770'
    owner: bareos
    group: bareos
  with_items: "{{ bareos_sd.location }}"

- name: Configure bareos-sd storage
  when: bareos_sd.storage is defined
  template:
    src: storage.conf.j2
    dest: /etc/bareos/bareos-sd.d/storage/{{ item.name }}.conf
    mode: '0640'
    owner: bareos
    group: bareos
  with_items: "{{ bareos_sd.storage }}"

- name: Configure bareos-sd director
  when: bareos_sd.director is defined
  template:
    src: director.conf.j2
    dest: /etc/bareos/bareos-sd.d/director/{{ item.name }}.conf
    mode: '0640'
    owner: bareos
    group: bareos
  with_items: "{{ bareos_sd.director }}"

- name: Configure bareos-sd devices
  when: bareos_sd.device is defined
  template:
    src: device.conf.j2
    dest: /etc/bareos/bareos-sd.d/device/{{ item.name }}.conf
    mode: '0640'
    owner: bareos
    group: bareos
  with_items: "{{ bareos_sd.device }}"

- name: Configure bareos-sd messages
  when: bareos_sd.messages is defined
  template:
    src: messages.conf.j2
    dest: /etc/bareos/bareos-sd.d/messages/{{ item.name }}.conf
    mode: '0640'
    owner: bareos
    group: bareos
  with_items: "{{ bareos_sd.messages }}"
