---
- import_tasks: install.yml
  tags:
    - install_bareos_sd
    - install
    - bareos_sd

- import_tasks: configure.yml
  tags:
    - configure_bareos_sd
    - configure
    - bareos_sd

- import_tasks: storage.yml
  when: bareos_sd.storage is defined
  tags:
    - configure_bareos_sd
    - bareos_sd_storage
    - bareos_sd

- import_tasks: director.yml
  when: bareos_sd.director is defined
  tags:
    - configure_bareos_sd
    - bareos_sd_director
    - bareos_sd

- import_tasks: device.yml
  when: bareos_sd.device is defined
  tags:
    - configure_bareos_sd
    - bareos_sd_device
    - bareos_sd

- import_tasks: messages.yml
  when: bareos_sd.messages is defined
  tags:
    - configure_bareos_sd
    - bareos_sd_messages
    - bareos_sd
