---
- name: Configure bareos-sd storage
  ansible.builtin.template:
    src: storage.conf.j2
    dest: /etc/bareos/bareos-sd.d/storage/{{ item.name }}.conf
    mode: '0640'
    owner: bareos
    group: bareos
  with_items: "{{ bareos_sd.storage }}"
  notify:
    - restart bareos-sd service

- name: Remove default bareos-sd configuration (unmanaged)
  ansible.builtin.file:
    path: /etc/bareos/bareos-sd.d/storage/{{ item }}
    state: absent
  with_items:
    - bareos-sd.conf
  notify:
    - restart bareos-sd service
