---
- name: Configure bareos-sd storage
  ansible.builtin.template:
    src: storage.conf.j2
    dest: /etc/bareos/bareos-sd.d/storage/{{ item.name }}.conf
    mode: '0640'
    owner: bareos
    group: bareos
  with_items: "{{ bareos_sd.storage }}"
  notify:
    - restart bareos-sd service

- name: Find unmanaged bareos-sd storage configurations
  ansible.builtin.find:
    paths: /etc/bareos/bareos-sd.d/storage
    file_type: file
    excludes: "{{ bareos_sd.storage | map(attribute='name') | product(['.conf']) | map('join') | flatten }}"
  register: fsout

- name: Remove unmanaged bareos-sd storage configurations
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ fsout.files | map(attribute='path') | unique }}"
  notify:
    - restart bareos-sd service
