---
- name: Create tls location if that need
  file: 
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: bareos
    group: bareos
  with_items:
    - "/etc/bareos/tls"

- name: Create storage location
  when: bareos_sd.location is defined
  file: 
    path: "{{ item.path }}"
    state: directory
    mode: '0770'
    owner: bareos
    group: bareos
  with_items: "{{ bareos_sd.location }}"

- name: Configure bareos-sd storage
  when: bareos_sd.storage is defined
  template:
    src: storage.conf.j2
    dest: /etc/bareos/bareos-sd.d/storage/{{ item.name }}.conf
    mode: '0640'
    owner: bareos
    group: bareos
  with_items: "{{ bareos_sd.storage }}"
  notify:
    - restart bareos-sd service
