---
- name: enable bareos-sd service
  ansible.builtin.service:
    name: bareos-sd
    enabled: true

- name: restart bareos-sd service
  ansible.builtin.service:
    name: bareos-sd
    state: restarted
